// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queue.proto

package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Priority int32

const (
	Priority_LOW  Priority = 0
	Priority_HIGH Priority = 1
)

var Priority_name = map[int32]string{
	0: "LOW",
	1: "HIGH",
}
var Priority_value = map[string]int32{
	"LOW":  0,
	"HIGH": 1,
}

func (x Priority) String() string {
	return proto.EnumName(Priority_name, int32(x))
}
func (Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{0}
}

// Authenticates the single connection
type AuthenticateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{0}
}
func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(dst, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	// True if the authentication was successful,
	// false otherwise
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{1}
}
func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(dst, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Puts a new message in the queue
type EnqueueRequest struct {
	// The actual task to enqueue
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The priority of the task
	Priority Priority `protobuf:"varint,2,opt,name=priority,proto3,enum=Priority" json:"priority,omitempty"`
	// What capabilities are required to handle the task
	RequiredCapabilities []string `protobuf:"bytes,3,rep,name=requiredCapabilities,proto3" json:"requiredCapabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueRequest) Reset()         { *m = EnqueueRequest{} }
func (m *EnqueueRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueRequest) ProtoMessage()    {}
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{2}
}
func (m *EnqueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueRequest.Unmarshal(m, b)
}
func (m *EnqueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueRequest.Marshal(b, m, deterministic)
}
func (dst *EnqueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueRequest.Merge(dst, src)
}
func (m *EnqueueRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueRequest.Size(m)
}
func (m *EnqueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueRequest proto.InternalMessageInfo

func (m *EnqueueRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *EnqueueRequest) GetPriority() Priority {
	if m != nil {
		return m.Priority
	}
	return Priority_LOW
}

func (m *EnqueueRequest) GetRequiredCapabilities() []string {
	if m != nil {
		return m.RequiredCapabilities
	}
	return nil
}

type EnqueueResponse struct {
	// The id of the created task
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnqueueResponse) Reset()         { *m = EnqueueResponse{} }
func (m *EnqueueResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueResponse) ProtoMessage()    {}
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{3}
}
func (m *EnqueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueResponse.Unmarshal(m, b)
}
func (m *EnqueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueResponse.Marshal(b, m, deterministic)
}
func (dst *EnqueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueResponse.Merge(dst, src)
}
func (m *EnqueueResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueResponse.Size(m)
}
func (m *EnqueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueResponse proto.InternalMessageInfo

func (m *EnqueueResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Removes a single message from the queue
type PopRequest struct {
	// What capabilities the client has available
	AvailableCapabilities []string `protobuf:"bytes,1,rep,name=availableCapabilities,proto3" json:"availableCapabilities,omitempty"`
	// If the server should wait for a message to come in, before returning
	// with a response
	WaitForMessage       bool     `protobuf:"varint,2,opt,name=waitForMessage,proto3" json:"waitForMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopRequest) Reset()         { *m = PopRequest{} }
func (m *PopRequest) String() string { return proto.CompactTextString(m) }
func (*PopRequest) ProtoMessage()    {}
func (*PopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{4}
}
func (m *PopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopRequest.Unmarshal(m, b)
}
func (m *PopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopRequest.Marshal(b, m, deterministic)
}
func (dst *PopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopRequest.Merge(dst, src)
}
func (m *PopRequest) XXX_Size() int {
	return xxx_messageInfo_PopRequest.Size(m)
}
func (m *PopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopRequest proto.InternalMessageInfo

func (m *PopRequest) GetAvailableCapabilities() []string {
	if m != nil {
		return m.AvailableCapabilities
	}
	return nil
}

func (m *PopRequest) GetWaitForMessage() bool {
	if m != nil {
		return m.WaitForMessage
	}
	return false
}

type PopResponse struct {
	// True if there was a message available
	HadResult bool `protobuf:"varint,3,opt,name=hadResult,proto3" json:"hadResult,omitempty"`
	// The actual message to process
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The id of the message
	// Should be returned with the acknowledge request
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopResponse) Reset()         { *m = PopResponse{} }
func (m *PopResponse) String() string { return proto.CompactTextString(m) }
func (*PopResponse) ProtoMessage()    {}
func (*PopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{5}
}
func (m *PopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopResponse.Unmarshal(m, b)
}
func (m *PopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopResponse.Marshal(b, m, deterministic)
}
func (dst *PopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopResponse.Merge(dst, src)
}
func (m *PopResponse) XXX_Size() int {
	return xxx_messageInfo_PopResponse.Size(m)
}
func (m *PopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PopResponse proto.InternalMessageInfo

func (m *PopResponse) GetHadResult() bool {
	if m != nil {
		return m.HadResult
	}
	return false
}

func (m *PopResponse) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PopResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AcknowledgeRequest struct {
	// The id of the message to acknowledge
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcknowledgeRequest) Reset()         { *m = AcknowledgeRequest{} }
func (m *AcknowledgeRequest) String() string { return proto.CompactTextString(m) }
func (*AcknowledgeRequest) ProtoMessage()    {}
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{6}
}
func (m *AcknowledgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcknowledgeRequest.Unmarshal(m, b)
}
func (m *AcknowledgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcknowledgeRequest.Marshal(b, m, deterministic)
}
func (dst *AcknowledgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcknowledgeRequest.Merge(dst, src)
}
func (m *AcknowledgeRequest) XXX_Size() int {
	return xxx_messageInfo_AcknowledgeRequest.Size(m)
}
func (m *AcknowledgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcknowledgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcknowledgeRequest proto.InternalMessageInfo

func (m *AcknowledgeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Returned when a message has been acknowledged
type AcknowledgeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcknowledgeResponse) Reset()         { *m = AcknowledgeResponse{} }
func (m *AcknowledgeResponse) String() string { return proto.CompactTextString(m) }
func (*AcknowledgeResponse) ProtoMessage()    {}
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{7}
}
func (m *AcknowledgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcknowledgeResponse.Unmarshal(m, b)
}
func (m *AcknowledgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcknowledgeResponse.Marshal(b, m, deterministic)
}
func (dst *AcknowledgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcknowledgeResponse.Merge(dst, src)
}
func (m *AcknowledgeResponse) XXX_Size() int {
	return xxx_messageInfo_AcknowledgeResponse.Size(m)
}
func (m *AcknowledgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcknowledgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcknowledgeResponse proto.InternalMessageInfo

type ErrorResponse struct {
	// What went wrong
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{8}
}
func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (dst *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(dst, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Wraps the requests for easier parsing on the socket layer
type RequestWrapper struct {
	RefId int32 `protobuf:"varint,10,opt,name=refId,proto3" json:"refId,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*RequestWrapper_Enqueue
	//	*RequestWrapper_Pop
	//	*RequestWrapper_Acknowledge
	//	*RequestWrapper_Authenticate
	Message              isRequestWrapper_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RequestWrapper) Reset()         { *m = RequestWrapper{} }
func (m *RequestWrapper) String() string { return proto.CompactTextString(m) }
func (*RequestWrapper) ProtoMessage()    {}
func (*RequestWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{9}
}
func (m *RequestWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestWrapper.Unmarshal(m, b)
}
func (m *RequestWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestWrapper.Marshal(b, m, deterministic)
}
func (dst *RequestWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestWrapper.Merge(dst, src)
}
func (m *RequestWrapper) XXX_Size() int {
	return xxx_messageInfo_RequestWrapper.Size(m)
}
func (m *RequestWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_RequestWrapper proto.InternalMessageInfo

type isRequestWrapper_Message interface {
	isRequestWrapper_Message()
}

type RequestWrapper_Enqueue struct {
	Enqueue *EnqueueRequest `protobuf:"bytes,1,opt,name=enqueue,proto3,oneof"`
}
type RequestWrapper_Pop struct {
	Pop *PopRequest `protobuf:"bytes,2,opt,name=pop,proto3,oneof"`
}
type RequestWrapper_Acknowledge struct {
	Acknowledge *AcknowledgeRequest `protobuf:"bytes,3,opt,name=acknowledge,proto3,oneof"`
}
type RequestWrapper_Authenticate struct {
	Authenticate *AuthenticateRequest `protobuf:"bytes,6,opt,name=authenticate,proto3,oneof"`
}

func (*RequestWrapper_Enqueue) isRequestWrapper_Message()      {}
func (*RequestWrapper_Pop) isRequestWrapper_Message()          {}
func (*RequestWrapper_Acknowledge) isRequestWrapper_Message()  {}
func (*RequestWrapper_Authenticate) isRequestWrapper_Message() {}

func (m *RequestWrapper) GetMessage() isRequestWrapper_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RequestWrapper) GetRefId() int32 {
	if m != nil {
		return m.RefId
	}
	return 0
}

func (m *RequestWrapper) GetEnqueue() *EnqueueRequest {
	if x, ok := m.GetMessage().(*RequestWrapper_Enqueue); ok {
		return x.Enqueue
	}
	return nil
}

func (m *RequestWrapper) GetPop() *PopRequest {
	if x, ok := m.GetMessage().(*RequestWrapper_Pop); ok {
		return x.Pop
	}
	return nil
}

func (m *RequestWrapper) GetAcknowledge() *AcknowledgeRequest {
	if x, ok := m.GetMessage().(*RequestWrapper_Acknowledge); ok {
		return x.Acknowledge
	}
	return nil
}

func (m *RequestWrapper) GetAuthenticate() *AuthenticateRequest {
	if x, ok := m.GetMessage().(*RequestWrapper_Authenticate); ok {
		return x.Authenticate
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RequestWrapper) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RequestWrapper_OneofMarshaler, _RequestWrapper_OneofUnmarshaler, _RequestWrapper_OneofSizer, []interface{}{
		(*RequestWrapper_Enqueue)(nil),
		(*RequestWrapper_Pop)(nil),
		(*RequestWrapper_Acknowledge)(nil),
		(*RequestWrapper_Authenticate)(nil),
	}
}

func _RequestWrapper_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RequestWrapper)
	// message
	switch x := m.Message.(type) {
	case *RequestWrapper_Enqueue:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Enqueue); err != nil {
			return err
		}
	case *RequestWrapper_Pop:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pop); err != nil {
			return err
		}
	case *RequestWrapper_Acknowledge:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Acknowledge); err != nil {
			return err
		}
	case *RequestWrapper_Authenticate:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Authenticate); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RequestWrapper.Message has unexpected type %T", x)
	}
	return nil
}

func _RequestWrapper_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RequestWrapper)
	switch tag {
	case 1: // message.enqueue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnqueueRequest)
		err := b.DecodeMessage(msg)
		m.Message = &RequestWrapper_Enqueue{msg}
		return true, err
	case 2: // message.pop
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PopRequest)
		err := b.DecodeMessage(msg)
		m.Message = &RequestWrapper_Pop{msg}
		return true, err
	case 3: // message.acknowledge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AcknowledgeRequest)
		err := b.DecodeMessage(msg)
		m.Message = &RequestWrapper_Acknowledge{msg}
		return true, err
	case 6: // message.authenticate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthenticateRequest)
		err := b.DecodeMessage(msg)
		m.Message = &RequestWrapper_Authenticate{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RequestWrapper_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RequestWrapper)
	// message
	switch x := m.Message.(type) {
	case *RequestWrapper_Enqueue:
		s := proto.Size(x.Enqueue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RequestWrapper_Pop:
		s := proto.Size(x.Pop)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RequestWrapper_Acknowledge:
		s := proto.Size(x.Acknowledge)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RequestWrapper_Authenticate:
		s := proto.Size(x.Authenticate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResponseWrapper struct {
	RefId int32 `protobuf:"varint,10,opt,name=refId,proto3" json:"refId,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*ResponseWrapper_Enqueue
	//	*ResponseWrapper_Pop
	//	*ResponseWrapper_Acknowledge
	//	*ResponseWrapper_Error
	//	*ResponseWrapper_Authenticate
	Message              isResponseWrapper_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ResponseWrapper) Reset()         { *m = ResponseWrapper{} }
func (m *ResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ResponseWrapper) ProtoMessage()    {}
func (*ResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_queue_7ac3e76a0189e465, []int{10}
}
func (m *ResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseWrapper.Unmarshal(m, b)
}
func (m *ResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseWrapper.Marshal(b, m, deterministic)
}
func (dst *ResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWrapper.Merge(dst, src)
}
func (m *ResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ResponseWrapper.Size(m)
}
func (m *ResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWrapper proto.InternalMessageInfo

type isResponseWrapper_Message interface {
	isResponseWrapper_Message()
}

type ResponseWrapper_Enqueue struct {
	Enqueue *EnqueueResponse `protobuf:"bytes,1,opt,name=enqueue,proto3,oneof"`
}
type ResponseWrapper_Pop struct {
	Pop *PopResponse `protobuf:"bytes,2,opt,name=pop,proto3,oneof"`
}
type ResponseWrapper_Acknowledge struct {
	Acknowledge *AcknowledgeResponse `protobuf:"bytes,3,opt,name=acknowledge,proto3,oneof"`
}
type ResponseWrapper_Error struct {
	Error *ErrorResponse `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}
type ResponseWrapper_Authenticate struct {
	Authenticate *AuthenticateResponse `protobuf:"bytes,6,opt,name=authenticate,proto3,oneof"`
}

func (*ResponseWrapper_Enqueue) isResponseWrapper_Message()      {}
func (*ResponseWrapper_Pop) isResponseWrapper_Message()          {}
func (*ResponseWrapper_Acknowledge) isResponseWrapper_Message()  {}
func (*ResponseWrapper_Error) isResponseWrapper_Message()        {}
func (*ResponseWrapper_Authenticate) isResponseWrapper_Message() {}

func (m *ResponseWrapper) GetMessage() isResponseWrapper_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ResponseWrapper) GetRefId() int32 {
	if m != nil {
		return m.RefId
	}
	return 0
}

func (m *ResponseWrapper) GetEnqueue() *EnqueueResponse {
	if x, ok := m.GetMessage().(*ResponseWrapper_Enqueue); ok {
		return x.Enqueue
	}
	return nil
}

func (m *ResponseWrapper) GetPop() *PopResponse {
	if x, ok := m.GetMessage().(*ResponseWrapper_Pop); ok {
		return x.Pop
	}
	return nil
}

func (m *ResponseWrapper) GetAcknowledge() *AcknowledgeResponse {
	if x, ok := m.GetMessage().(*ResponseWrapper_Acknowledge); ok {
		return x.Acknowledge
	}
	return nil
}

func (m *ResponseWrapper) GetError() *ErrorResponse {
	if x, ok := m.GetMessage().(*ResponseWrapper_Error); ok {
		return x.Error
	}
	return nil
}

func (m *ResponseWrapper) GetAuthenticate() *AuthenticateResponse {
	if x, ok := m.GetMessage().(*ResponseWrapper_Authenticate); ok {
		return x.Authenticate
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResponseWrapper) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResponseWrapper_OneofMarshaler, _ResponseWrapper_OneofUnmarshaler, _ResponseWrapper_OneofSizer, []interface{}{
		(*ResponseWrapper_Enqueue)(nil),
		(*ResponseWrapper_Pop)(nil),
		(*ResponseWrapper_Acknowledge)(nil),
		(*ResponseWrapper_Error)(nil),
		(*ResponseWrapper_Authenticate)(nil),
	}
}

func _ResponseWrapper_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResponseWrapper)
	// message
	switch x := m.Message.(type) {
	case *ResponseWrapper_Enqueue:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Enqueue); err != nil {
			return err
		}
	case *ResponseWrapper_Pop:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pop); err != nil {
			return err
		}
	case *ResponseWrapper_Acknowledge:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Acknowledge); err != nil {
			return err
		}
	case *ResponseWrapper_Error:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *ResponseWrapper_Authenticate:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Authenticate); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ResponseWrapper.Message has unexpected type %T", x)
	}
	return nil
}

func _ResponseWrapper_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResponseWrapper)
	switch tag {
	case 1: // message.enqueue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnqueueResponse)
		err := b.DecodeMessage(msg)
		m.Message = &ResponseWrapper_Enqueue{msg}
		return true, err
	case 2: // message.pop
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PopResponse)
		err := b.DecodeMessage(msg)
		m.Message = &ResponseWrapper_Pop{msg}
		return true, err
	case 3: // message.acknowledge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AcknowledgeResponse)
		err := b.DecodeMessage(msg)
		m.Message = &ResponseWrapper_Acknowledge{msg}
		return true, err
	case 4: // message.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorResponse)
		err := b.DecodeMessage(msg)
		m.Message = &ResponseWrapper_Error{msg}
		return true, err
	case 6: // message.authenticate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthenticateResponse)
		err := b.DecodeMessage(msg)
		m.Message = &ResponseWrapper_Authenticate{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ResponseWrapper_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResponseWrapper)
	// message
	switch x := m.Message.(type) {
	case *ResponseWrapper_Enqueue:
		s := proto.Size(x.Enqueue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseWrapper_Pop:
		s := proto.Size(x.Pop)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseWrapper_Acknowledge:
		s := proto.Size(x.Acknowledge)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseWrapper_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseWrapper_Authenticate:
		s := proto.Size(x.Authenticate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "AuthenticateResponse")
	proto.RegisterType((*EnqueueRequest)(nil), "EnqueueRequest")
	proto.RegisterType((*EnqueueResponse)(nil), "EnqueueResponse")
	proto.RegisterType((*PopRequest)(nil), "PopRequest")
	proto.RegisterType((*PopResponse)(nil), "PopResponse")
	proto.RegisterType((*AcknowledgeRequest)(nil), "AcknowledgeRequest")
	proto.RegisterType((*AcknowledgeResponse)(nil), "AcknowledgeResponse")
	proto.RegisterType((*ErrorResponse)(nil), "ErrorResponse")
	proto.RegisterType((*RequestWrapper)(nil), "RequestWrapper")
	proto.RegisterType((*ResponseWrapper)(nil), "ResponseWrapper")
	proto.RegisterEnum("Priority", Priority_name, Priority_value)
}

func init() { proto.RegisterFile("queue.proto", fileDescriptor_queue_7ac3e76a0189e465) }

var fileDescriptor_queue_7ac3e76a0189e465 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x86, 0x6d, 0xa7, 0x6d, 0xe2, 0x71, 0x3e, 0x27, 0xda, 0x24, 0x92, 0xf5, 0x09, 0x44, 0xb0,
	0xa0, 0x0a, 0x3f, 0x5a, 0xa1, 0x80, 0x04, 0x82, 0xa3, 0x16, 0x15, 0x5c, 0x89, 0x8a, 0x6a, 0x25,
	0x54, 0x89, 0xb3, 0x4d, 0x3c, 0xb4, 0x0b, 0x69, 0xec, 0xec, 0xda, 0x44, 0x5c, 0x00, 0x17, 0xc2,
	0x29, 0xd7, 0xc7, 0x05, 0xa0, 0xac, 0x7f, 0x62, 0x07, 0x2b, 0x67, 0x9e, 0x9d, 0xdd, 0x7d, 0xe7,
	0x79, 0x67, 0xd6, 0xe0, 0xac, 0x52, 0x4c, 0x91, 0xc6, 0x32, 0x4a, 0x22, 0xff, 0x02, 0x06, 0x27,
	0x69, 0x72, 0x83, 0xcb, 0x44, 0xcc, 0x79, 0x82, 0x0c, 0x57, 0x29, 0xaa, 0x84, 0xfc, 0x0f, 0x9d,
	0x54, 0xa1, 0x5c, 0xf2, 0x5b, 0xf4, 0xcc, 0xb1, 0x39, 0xb1, 0x59, 0x19, 0x6f, 0x72, 0x31, 0x57,
	0x6a, 0x1d, 0xc9, 0xd0, 0xb3, 0xb2, 0x5c, 0x11, 0xfb, 0xcf, 0x60, 0x58, 0xbf, 0x4e, 0xc5, 0xd1,
	0x52, 0x21, 0xf1, 0xa0, 0xad, 0xd2, 0xf9, 0x1c, 0x95, 0xd2, 0xd7, 0x75, 0x58, 0x11, 0xfa, 0x3f,
	0x4d, 0x70, 0xcf, 0x96, 0xba, 0xa4, 0x42, 0xdc, 0x83, 0xf6, 0x2d, 0x2a, 0xc5, 0xaf, 0x33, 0xed,
	0x2e, 0x2b, 0x42, 0xf2, 0x10, 0x3a, 0xb1, 0x14, 0x91, 0x14, 0xc9, 0x0f, 0x2d, 0xed, 0x4e, 0x6d,
	0x7a, 0x99, 0x2f, 0xb0, 0x32, 0x45, 0xa6, 0x30, 0x94, 0xb8, 0x4a, 0x85, 0xc4, 0xf0, 0x2d, 0x8f,
	0xf9, 0x4c, 0x2c, 0x44, 0x22, 0x50, 0x79, 0xad, 0x71, 0x6b, 0x62, 0xb3, 0xc6, 0x9c, 0x7f, 0x1f,
	0x7a, 0x65, 0x19, 0x79, 0xd1, 0x2e, 0x58, 0x22, 0xcc, 0xf1, 0x2d, 0x11, 0xfa, 0x5f, 0x01, 0x2e,
	0xa3, 0xb8, 0xa8, 0xf2, 0x05, 0x8c, 0xf8, 0x77, 0x2e, 0x16, 0x7c, 0xb6, 0xc0, 0x9a, 0x8a, 0xa9,
	0x55, 0x9a, 0x93, 0xe4, 0x18, 0xdc, 0x35, 0x17, 0xc9, 0xbb, 0x48, 0x5e, 0xe4, 0x88, 0x96, 0xf6,
	0x63, 0x67, 0xd5, 0xff, 0x04, 0x8e, 0xd6, 0xca, 0x4b, 0xb9, 0x03, 0xf6, 0x0d, 0x0f, 0x19, 0xaa,
	0x74, 0x91, 0x78, 0x2d, 0x7d, 0x62, 0xbb, 0xb0, 0xc7, 0xb0, 0x0c, 0xc1, 0x2a, 0x11, 0x1e, 0x00,
	0x39, 0x99, 0x7f, 0x5b, 0x46, 0xeb, 0x05, 0x86, 0xd7, 0xa5, 0xe1, 0xbb, 0xa0, 0x23, 0x18, 0xd4,
	0x76, 0x65, 0x45, 0xf8, 0x8f, 0xe0, 0xbf, 0x33, 0x29, 0x23, 0x59, 0xed, 0x6a, 0x55, 0xd7, 0x2e,
	0x75, 0xfd, 0x3f, 0x26, 0xb8, 0xf9, 0xed, 0x57, 0x92, 0xc7, 0x31, 0x4a, 0x32, 0x84, 0x43, 0x89,
	0x5f, 0xce, 0x43, 0x0f, 0xc6, 0xe6, 0xe4, 0x90, 0x65, 0x01, 0x79, 0x02, 0x6d, 0xcc, 0x6c, 0xd7,
	0x57, 0x38, 0xd3, 0x1e, 0xad, 0x4f, 0x43, 0x60, 0xb0, 0x62, 0x07, 0xb9, 0x07, 0xad, 0x38, 0x8a,
	0x35, 0x8e, 0x33, 0x75, 0xe8, 0xb6, 0x19, 0x81, 0xc1, 0x36, 0x19, 0xf2, 0x12, 0x1c, 0xbe, 0x2d,
	0x5c, 0x1b, 0xe5, 0x4c, 0x07, 0xf4, 0x5f, 0xe4, 0xc0, 0x60, 0xd5, 0x9d, 0xe4, 0x35, 0x74, 0x79,
	0x65, 0x6e, 0xbd, 0x23, 0x7d, 0x72, 0x48, 0x1b, 0xde, 0x46, 0x60, 0xb0, 0xda, 0xde, 0x53, 0xbb,
	0x74, 0xc1, 0xff, 0x65, 0x41, 0xaf, 0x70, 0x67, 0x3f, 0xf7, 0xd3, 0x5d, 0xee, 0x3e, 0xdd, 0x19,
	0xbf, 0x2a, 0xf8, 0xb8, 0x0a, 0xde, 0xa5, 0x95, 0xc9, 0x28, 0xc8, 0x5f, 0x35, 0x91, 0x0f, 0x69,
	0x43, 0x1b, 0x77, 0xd1, 0x8f, 0xe1, 0x10, 0x37, 0x5d, 0xf5, 0x0e, 0xf4, 0x19, 0x97, 0xd6, 0x7a,
	0x1c, 0x18, 0x2c, 0x4b, 0x93, 0x37, 0x8d, 0x16, 0x8d, 0x68, 0xd3, 0x7b, 0xdf, 0xe3, 0xd1, 0xe3,
	0xbb, 0xd0, 0x29, 0x9e, 0x2c, 0x69, 0x43, 0xeb, 0xc3, 0xc7, 0xab, 0xbe, 0x41, 0x3a, 0x70, 0x10,
	0x9c, 0xbf, 0x0f, 0xfa, 0xe6, 0xe9, 0xe0, 0x73, 0x7b, 0x26, 0x35, 0xf5, 0x6f, 0xab, 0xf8, 0x9a,
	0x1d, 0xe9, 0x9f, 0xd5, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0xef, 0x1c, 0xb2, 0xbb,
	0x04, 0x00, 0x00,
}
